---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
    tag: latest

inputs:
- name: capi-release
- name: timeline-repo

run:
  path: timeline-repo/ci/tasks/capi-list.sh
